[package]
name = "emoji-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3.3"
emojis = "0.5.2"
urlencoding = "2.1.2"
pretty_env_logger = "0.4.0"
unicode-segmentation = "1.10.1"
tokio = { version = "1", features = ["full"] }
