[package]
name = "shuttle"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
warp = "0.3.3"
shuttle-service = { version = "0.10.0", features = ["web-warp"] }

emoji-auth = { path = "../emoji-auth" }
